# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults"

    - name: Test Report
      uses: dorny/test-reporter@v1.6.0
      if: ${{ always() }}
      with:
        name: DotNET Tests
        path: "**/TestResults/*.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: Benchmark
      run: dotnet run --project ./tests/Api.Project.Template.Tests.Benchmark -c Release

    - name: Upload Benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: BenchmarkDotNet.Artifacts/results/*.md
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      